//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

enum ___VARIABLE_sceneName___Models {
    
    enum Something {
        struct Request: Codable {
            
        }
        
        struct Response: StandardResponseProtocol {
            let Code: String
            let Message: String
        }
        
        struct ViewModel {
            
        }
    }
    
}
