//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation
import Moya

enum ___VARIABLE_sceneName___Request {
    
}

//extension ___VARIABLE_sceneName___Request: TargetType {
//
//    var baseURL: URL {
//        URL(string: "")!
//    }
//    
//    var path: String {
//        switch self {
//        case .
//            return ""
//        }
//    }
//    
//    var method: Moya.Method {
//        .post
//    }
//    
//    var sampleData: Data {
//        Data()
//    }
//    
//    var task: Task {
//        switch self {
//        case let .:
//            return .requestParameters(parameters: ["": ], encoding: URLEncoding.default)
//        }
//    }
//    
//    var headers: [String : String]? {
//        return ["content-type": "application/x-www-form-urlencoded"]
//    }
//
//}
